version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:15-alpine
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 5432:5432
    volumes:
      - mail_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  mail_assistant:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres
    command: sh -c "/wait && npx prisma db push && npm run start"
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      NEXT_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      WAIT_HOSTS: ${POSTGRES_HOST}:${POSTGRES_PORT}
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_BEFORE: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
volumes:
  mail_postgres:
